# Generated by Django 2.2.28 on 2022-11-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expires',
        ),
    ]
