# Generated by Django 2.0.7 on 2018-07-24 22:17

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adverts.Advert')),
                ('duration', models.CharField(choices=[('ft', 'Fulltime'), ('pt', 'Parttime')], default='ft', max_length=2)),
                ('countries', django_countries.fields.CountryField(default='EN', max_length=11, multiple=True)),
                ('salary', models.PositiveIntegerField()),
            ],
            bases=('adverts.advert',),
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.Location'),
        ),
    ]
