# Generated by Django 2.0.7 on 2018-07-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adverts.Advert')),
            ],
            bases=('adverts.advert',),
        ),
        migrations.CreateModel(
            name='GiftsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('name_en', models.CharField(max_length=42, null=True)),
                ('name_ru', models.CharField(max_length=42, null=True)),
                ('name_pl', models.CharField(max_length=42, null=True)),
                ('name_ua', models.CharField(max_length=42, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='gifts_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.GiftsType'),
        ),
    ]
