# Generated by Django 2.2.24 on 2021-10-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='per',
            field=models.CharField(choices=[('h', 'per hour'), ('w', 'per week'), ('y', 'annual salary'), ('m', 'per mile')], default='h', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('f', 'full-time'), ('p', 'part-time'), ('c', 'casual')], default='f', max_length=1),
        ),
    ]
