# Generated by Django 2.2.28 on 2022-11-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expires',
        ),
    ]
