# Generated by Django 2.2.28 on 2022-10-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('name_en', models.CharField(max_length=42, null=True)),
                ('name_ru', models.CharField(max_length=42, null=True)),
                ('name_pl', models.CharField(max_length=42, null=True)),
                ('name_uk', models.CharField(max_length=42, null=True)),
                ('icon', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='salary',
        )
    ]
