# Generated by Django 2.2.28 on 2022-10-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType', verbose_name='service type'),
        ),
    ]
