# Generated by Django 2.0.7 on 2018-07-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adverts.Advert')),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('price', models.PositiveIntegerField()),
                ('pet_policy', models.CharField(choices=[('1', 'None'), ('2', 'Dogs'), ('3', 'Cats'), ('4', 'Dogs adn Cats'), ('5', 'Any')], default='1', max_length=1)),
                ('furnished', models.BooleanField()),
                ('prefer_sex', models.CharField(choices=[('a', 'any'), ('g', 'woman'), ('b', 'man')], default='a', max_length=1)),
                ('attached', models.ImageField(blank=True, max_length=1000, null=True, upload_to='media/rents', verbose_name='Imagen')),
                ('address', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.Location')),
            ],
            bases=('adverts.advert',),
        ),
    ]
