# Generated by Django 2.2.24 on 2021-07-11 16:36

import apps.promotions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('h', 'Header'), ('rs', 'Right Sidebar'), ('ls', 'Left Sidebar')], max_length=2)),
            ],
            options={
                'ordering': ('area',),
            },
        ),
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('paid', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'Extra small'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra large')], max_length=2)),
                ('local', models.CharField(choices=[('en', 'English'), ('uk', 'Ukraine'), ('ru', 'Russian'), ('pl', 'Polish')], default='en', max_length=2)),
                ('image', models.ImageField(upload_to=apps.promotions.models.user_directory_path)),
                ('areas', models.ManyToManyField(to='promotions.Area')),
                ('promote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='promotions.Promote')),
            ],
        ),
    ]
