# Generated by Django 2.0.7 on 2018-07-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('advert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adverts.Advert')),
                ('price', models.PositiveIntegerField()),
            ],
            bases=('adverts.advert',),
        ),
    ]
